In [1]:
import numpy as np

def solve_linear_equation(A, b):
    # enter your code here, and remove the following line (30%)
    rankA = np.linalg.matrix_rank(A)
    arrayAb = np.hstack((A,b))
    rankAb = np.linalg.matrix_rank(arrayAb)
    columnA =  A.shape[1]
    if rankA == rankAb:
        print(' 𝐀x = 𝐛 is consistent.')
    if rankA == rankAb and rankA == columnA:
        return 1
    if rankA == rankAb and rankA < columnA:
        return 0
    if rankA < rankAb:
        return -1
    return 0

def flag_to_message(flag):
   if flag == 1:
     print('The linear system Ax=b has only one solution.')
   elif flag == 0:
     print('The linear system Ax=b has infinitely many solutions.')
   elif flag == -1:
     print('The linear system Ax=b has no solutions.')
   else:
     print('Unknown flag!')

def get_input_data(input_id):
   if input_id == 'case1': 
     A = np.array([[3, 2, -1], [6, -1, 3], [1, 10, -2]])
     b = np.array([[-7], [-4], [2]])
   elif input_id == 'case2':
     A = np.array([[4, -1, 3], [21, -4, 18], [-9, 1, -9]])
     b = np.array([[5], [7], [-8]])
   elif input_id == 'case3':
     A = np.array([[7, -4, 1], [3, 2, -1], [5, 12, -5]])
     b = np.array([[-15], [-5], [-5]])
   return A, b

if __name__ == '__main__':
   for case in ['case1', 'case2', 'case3']:
     A, b = get_input_data(case)
     print(case)
     print('A =', A, 'b =', b.T)
     flag = solve_linear_equation(A, b)
     flag_to_message(flag)
     if flag == 1:
        print('The solution is ', np.linalg.solve(A, b))
     print()

case1
A = [[ 3  2 -1]
 [ 6 -1  3]
 [ 1 10 -2]] b = [[-7 -4  2]]
 𝐀x = 𝐛 is consistent.
The linear system Ax=b has only one solution.
The solution is  [[-2.]
 [ 1.]
 [ 3.]]

case2
A = [[ 4 -1  3]
 [21 -4 18]
 [-9  1 -9]] b = [[ 5  7 -8]]
The linear system Ax=b has no solutions.

case3
A = [[ 7 -4  1]
 [ 3  2 -1]
 [ 5 12 -5]] b = [[-15  -5  -5]]
 𝐀x = 𝐛 is consistent.
The linear system Ax=b has infinitely many solutions.



In [ ]:
# Can we use np.linalg.solve() to determine whether 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

# Answer:我認為是不行的，因為np.linalg.solve()只能在A矩陣為方陣時才可使用，若A為非方陣會出現error，
# 所以此function無法決定𝐀𝐱=𝐛是否consistent，還有np.linalg.solve()若A為不可逆矩陣時也會出現錯誤，但
# 不可逆矩陣不代表Ax=b就是無解，所以無法只利用np.linalg.solve()這個function來判斷。

In [ ]:
# Given matrix 𝐀 of dimension (m,n). If rank(𝐀)=𝑛, can we infer that 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

# Answer：我認為是可以的，rank(𝐀)=n表示A矩陣式可逆的，存在A的反矩陣，以下為證明。
# 證明：(A-1)表示為A的反矩陣。Ax=b ⟹ (A−1)Ax=(A−1)b ⟹ x=(A−1)b，得x有唯一解，表示𝐀𝐱=𝐛 is consistent。